---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r message = FALSE}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

```{r}
data("ny_noaa")

clean_df = ny_noaa %>% 
  janitor::clean_names() %>% 
  mutate(
    year = lubridate::year(date),
    month = lubridate::month(date),
    day = lubridate::day(date),
    prcp = prcp / 10,
    snow = snow / 10,
    snwd = snwd / 10,
    tmax = as.numeric(tmax) / 10,
    tmin = as.numeric(tmin) / 10
  )
```


Column {data-width=650}
-----------------------------------------------------------------------

### Mean temperature for each station across years for January

```{r message = FALSE, warning = FALSE}
clean_df %>% 
  filter(month == 1) %>% 
  mutate(
    month = case_when(
      month == 1 ~ "January"
    )
  ) %>% 
  group_by(year, month, id) %>% 
  summarise(mean_tmax = mean(tmax), na.rm = TRUE) %>% 
  plot_ly(
    x = ~year, y = ~mean_tmax, type = "scatter", mode = "markers",
    color = ~id
  ) %>% 
  layout(
    xaxis = list(title = "Year"),
    yaxis = list(title = "Mean Tmax"),
     showlegend = FALSE
  )
```


Column {data-width=350}
-----------------------------------------------------------------------

### Distribution of Total Snowfall by Month (2008)

```{r message = FALSE, warning = FALSE}
clean_df %>% 
  filter(year == 2008) %>%
  group_by(month, id) %>% 
  summarise(total_snow = sum(snow, na.rm = TRUE)) %>% 
  plot_ly(
    x = ~as.factor(month),
    y = ~total_snow,
    type = "box"
  ) %>%
  layout(
    xaxis = list(title = "Month"),
    yaxis = list(title = "Total Snowfall"),
    showlegend = FALSE
  )

```

### Mean Precipitation for Station (US1NYAB0001) across Months

```{r message = FALSE, warning = FALSE}
clean_df %>% 
  filter(id == "US1NYAB0001") %>% 
  group_by(month) %>% 
  summarise(mean_tmax = mean(prcp, na.rm = TRUE)) %>% 
  plot_ly(
    x = ~month, y = ~mean_tmax, type = "bar"
  ) %>% 
  layout(
    xaxis = list(title = "Month"),
    yaxis = list(title = "Mean Precipitation")
  )
```
